Zechiani\DataTableBundle\Entity\Demo:
  type: entity
  table: zechiani_bundle_datatable
  id:
    id:
      type: integer
      nullable: false
      unsigned: false
      comment: ''
      id: true
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      nullable: false
      length: 60
      fixed: false
      comment: ''
    code:
      type: string
      nullable: false
      length: 30
      fixed: false
      comment: ''
